/* -*- C++ -*-
 *
 *  ATTENTION: DO NOT INCLUDE THIS FILE DIRECTLY!
 *
 *  Instead you should include some file that includes this file, like
 *  AST.h.
 *
 *  See http://www.drdobbs.com/the-new-c-x-macros/184401387 .
 */

 // Expressions:

X(abstraction)
X(application)
X(fix)
X(let)
X(reference)
X(schema)
X(variable)
X(olapAggregate)

 // Constants:

X(cnull)
X(creal)
X(cstring)
X(cboolean)
X(cinteger)

 // Statements:

X(module)
X(insertArray)
X(selectArray)
X(namedExpr)
X(groupByClause)
X(joinClause)
X(regridClause)
X(regridDimension)
X(redimensionClause)
X(thinClause)
X(thinDimension)
X(windowClause)
X(windowDimensionRange)
X(updateArray)
X(update)

 // Miscellaneous:

X(binding)
X(attribute)
X(dimension)
X(asterisk)
X(questionMark)
X(list)
X(kwarg)
X(nestedArgs)
X(popNestedArgs)
X(distribution)
X(objectName)
